-- Add source column to flashcards table
ALTER TABLE flashcards 
ADD COLUMN source text CHECK (source IN ('ai-full', 'ai-edited', 'manual')) NOT NULL;

-- Add comment to the column
COMMENT ON COLUMN flashcards.source IS 'Source of the flashcard: ai-full (generated by AI), ai-edited (AI-generated but edited by user), manual (created by user)';

-- Update existing records to have 'manual' as source
UPDATE flashcards SET source = 'manual' WHERE source IS NULL;

-- Make the column NOT NULL after updating existing records
ALTER TABLE flashcards 
ALTER COLUMN source SET NOT NULL; 